# Generated by Django 4.1.7 on 2023-03-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soft_mark_cloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='naaas',
        ),
    ]
