# Generated by Django 4.1.7 on 2023-03-21 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soft_mark_cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key_id', models.CharField(max_length=256)),
                ('aws_secret_access_key', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aws_access_key_id')},
            },
        ),
    ]
