# Generated by Django 4.2 on 2023-04-14 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soft_mark_cloud', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscredentials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
